class Constants {
  Constants._();

  static const REST_CLIENT_CONNECT_TIMEOUT = 30000;
  static const REST_CLIENT_RECEIVE_TIMEOUT = 30000;

  static const LOCAL_STORAGE_ACCESS_TOKEN_KEY =
      'LOCAL_STORAGE_ACCESS_TOKEN_KEY';
  static const LOCAL_STORAGE_REFRESH_TOKEN_KEY =
      '/LOCAL_STORAGE_REFRESH_TOKEN_KEY/';
  static const LOCAL_STORAGE_USER_LOGGED_DATA_KEY =
      'LOCAL_STORAGE_USER_LOGGED_DATA_KEY';
}
